A notebook to convince myself of things.

In [2]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [9]:
X = np.array([[1],
             [2],
             [3],
             [4]])
print(X.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [15]:
b = np.arange(10)
print(b)
print(b.reshape(-1,2))
print(b.reshape(-1,5))
print(b.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
c = np.arange(5)
print(np.array([1,2,3]).reshape(1,-1).shape)
print(c)
print(c.reshape(-1,1).shape)
print(c.reshape(1,-1))

(1, 3)
[0 1 2 3 4]
(5, 1)
[[0 1 2 3 4]]


# COMP9444 Refresher

In [12]:
a = np.array([1,2,3])
print(type(a)) # returns <class 'numpy.ndarray'>
print(a.shape) # (1,3)
# no, it prints (3,)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape) # (3,2)
# again, you are incorrect: (2,3)

a = np.zeros(4) # array(0,0,0,0) -> NOPE
print(a)
a = np.zeros((2,2))
print(a)
b = np.zeros((1,2))
print(b) # [0,0]
# again, wrong: [[0,0]]
c = np.full((2,2), 7)
print(c)
d = np.eye(2)
print(d)

e = np.random.random((2,2))
print(e)


<class 'numpy.ndarray'>
(3,)
(2, 3)
[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[0. 0.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.09309175 0.59335963]
 [0.61022966 0.57365187]]


In [20]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.shape) # (3,4)
# you're getting it now; (rows, cols)

# want [[2,3],[6,7]]
b = a[:2,1:3]
print(a[0,1])
b[0,0] = 77 # this slice will be the same data as a
print(a[0,1])




(3, 4)
2
77


You can also mix integer with slice indexing, however doing so will yield an array of lower rank than the original array

In [26]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# we can make the same distinction when accessing columns of an array
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


I personally find indexing quite confusing, it has always been a problem for me.
study: when you index into numpy arrays using slicing, the resultting array view will ALWAYS be a subarray of the original array.
    this is not the case when you use *integer array indexing*.

In [32]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
# integer array indexing
print(a[[0,1,2],[0,1,0]])
# which is equivalent to:
print(np.array([a[0,0], a[1,1], a[2,0]]))

# to get [2 2] spit out you would then use the following 2 methods:
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

(3, 2)
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [41]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0,2,0,1])

print(a[np.arange(4), b])

# = a[[0,1,2,3], [0,2,0,1]]
print(np.arange(4))

# we can even mutate with
a[np.arange(4), b] += 10
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[0 1 2 3]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


we can also do **boolean array indexing**

In [44]:
# this type of indexing is used to select the elements that satisfy some sort of condition

a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a > 2)

print(bool_idx)
print(a[bool_idx]) # creates a rank 1 array of all the True corresponding values

print(a[a > 2]) # compressed into 1 statement!


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# Datatypes

In [55]:
x = np.array([[1,2]])
print(x.shape) # (1,2)
print(x)

# but, shit is weird when you have
x = np.array([1,2])
print(x.shape) # (2,)
print(x)

print(x.dtype)
print(type(x))

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2], dtype=np.int64)
print(x.dtype)

(1, 2)
[[1 2]]
(2,)
[1 2]
int64
<class 'numpy.ndarray'>
float64
int64


# Array Math

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

the above 2 snippets are from Alan Blair. I understand them, so don't really want to retype them.
but one thing I did not know was the equivalence of `x.dot(v)` and `np.dot(x,v)`

In [60]:
# the sum function

x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))
print(x.sum()) # interesting, this and the line above are equivalent.
print(x.sum(axis=0)) # also rank 1
print(x.sum(axis=1)) # interesting, this is still rank 1


[[1 2]
 [3 4]]
10
10
[4 6]
[3 7]


In [61]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[1 2 3]
[1 2 3]


# Broadcasting

In [67]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # empty matrix with same shape as x

for i in range(4):
    y[i:] = x[i:] + v
    
print(y)

# we then realise this is equivalent to stacking v's and computing explicit summation:
vv = np.tile(v, (4,1))
y = x + vv
print(y)

# or finally we could just leverage broadcasting:
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
