## 2.1

In [4]:
import torch

In [6]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [7]:
x.numel() # num elements; presumably

12

In [8]:
len(x)

12

In [11]:
x.shape # no brackets! it's an attribute of the tensor not a method.

torch.Size([12])

In [12]:
X = x.reshape(3, 4) # == x.reshape(3, -1) == x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones((2,3,4)), len(torch.ones((2,3,4))) # seems that length is just along the 0th axis.

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 2)

In [17]:
torch.randn(3,4) # standard deviation = 1, mean = 0

tensor([[-0.8725,  1.0880,  2.1401,  0.2476],
        [ 0.9554,  0.5242, -1.0524, -2.1604],
        [ 0.5442,  0.0042,  0.6839,  0.7259]])

In [18]:
X[-1], X[1:3] # applied along axis 0.

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [19]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [22]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [24]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3], [1,2,3,4], [4,3,2,1]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
X == Y, X < Y, X > Y, X >= Y, X <= Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[False,  True, False,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True,  True,  True,  True],
         [False, False, False, False],
         [False, False, False, False]]))

In [30]:
X.sum()

tensor(66.)

In [32]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [33]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [36]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [39]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 132091087213568
id(Z): 132091087213568


In [42]:
before = id(X)
X += Y
id(X) == before

True

In [43]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [44]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [56]:
d = torch.arange(16).reshape((4,2,-1))
e = torch.arange(2) # I do not understand n-dimensional broadcasting!
d, e, d + e

(tensor([[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 8,  9],
          [10, 11]],
 
         [[12, 13],
          [14, 15]]]),
 tensor([0, 1]),
 tensor([[[ 0,  2],
          [ 2,  4]],
 
         [[ 4,  6],
          [ 6,  8]],
 
         [[ 8, 10],
          [10, 12]],
 
         [[12, 14],
          [14, 16]]]))

## 2.2 Data Preprocessing

In [57]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
    NA,NA,127500
    2,NA,106000
    4,Slate,178100
    NA,NA,140000''')

In [58]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

  NumRooms RoofType   Price
0       NA      NaN  127500
1        2      NaN  106000
2        4    Slate  178100
3       NA      NaN  140000


In [60]:
inputs , targets = data.iloc[:, 0:-1], data.iloc[:, -1]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms_    2  NumRooms_    4  NumRooms_    NA  NumRooms_nan  \
0           False           False             True         False   
1            True           False            False         False   
2           False            True            False         False   
3           False           False             True         False   

   RoofType_Slate  RoofType_nan  
0           False          True  
1           False          True  
2            True         False  
3           False          True  


In [61]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms_    2  NumRooms_    4  NumRooms_    NA  NumRooms_nan  \
0           False           False             True         False   
1            True           False            False         False   
2           False            True            False         False   
3           False           False             True         False   

   RoofType_Slate  RoofType_nan  
0           False          True  
1           False          True  
2            True         False  
3           False          True  


In [62]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[0., 0., 1., 0., 0., 1.],
         [1., 0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 1., 0.],
         [0., 0., 1., 0., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## 2.3 Linear Algebra

In [66]:
A = torch.arange(6).reshape(2,-1)
A.T

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [67]:
B = A.clone()
B

tensor([[0, 1, 2],
        [3, 4, 5]])

In [69]:
A * B # hadamard product

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [81]:
A, A.sum(axis=0), A.sum(axis=1)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([3, 5, 7]),
 tensor([ 3, 12]))

In [82]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3],
         [12]]),
 torch.Size([2, 1]))

In [83]:
# an artifact of maintaining the shape is:
A / sum_A # where now the rows sum to 1.

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [84]:
A.cumsum(axis=0)

tensor([[0, 1, 2],
        [3, 5, 7]])

In [88]:
y = torch.ones(3, dtype = torch.float32)
x = torch.arange(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [89]:
torch.sum(x*y) # equiv to the dot product.

tensor(3.)

In [92]:
x = torch.arange(3, )
A.shape, x.shape, torch.mv(A, x), A@x # mv -> matrix vector multiplication.

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5, 14]), tensor([ 5, 14]))

In [101]:
B = torch.ones((3,4), dtype=torch.int64) # i need to be more careful about the initialisation data types.
torch.mm(A, B), A@B

(tensor([[ 3,  3,  3,  3],
         [12, 12, 12, 12]]),
 tensor([[ 3,  3,  3,  3],
         [12, 12, 12, 12]]))

In [102]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [103]:
torch.abs(u).sum()

tensor(7.)

In [105]:
torch.norm(torch.ones((4,9)))

tensor(6.)