A notebook to convince myself of things.

In [5]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [9]:
X = np.array([[1],
             [2],
             [3],
             [4]])
print(X.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [15]:
b = np.arange(10)
print(b)
print(b.reshape(-1,2))
print(b.reshape(-1,5))
print(b.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
c = np.arange(5)
print(np.array([1,2,3]).reshape(1,-1).shape)
print(c)
print(c.reshape(-1,1).shape)
print(c.reshape(1,-1))

(1, 3)
[0 1 2 3 4]
(5, 1)
[[0 1 2 3 4]]
