In [2]:
import torch

In [3]:
import numpy as np

In [4]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)
np_array = np.array(data)
print(np_array)
x_data = torch.from_numpy(np_array)
print(x_data)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [5]:
x_data = torch.tensor(data, dtype=torch.float)
print(x_data)

tensor([[1., 2.],
        [3., 4.]])


In [6]:
x_data = torch.tensor(data, dtype=torch.bool)
print(x_data)

tensor([[True, True],
        [True, True]])


In [7]:
initial_tensor = torch.tensor([[4., 5.], [6., 7.]])
print(initial_tensor)

# Initialise a new tensor of 1s
new_tensor_ones = torch.ones_like(initial_tensor)
print(new_tensor_ones)

# Initialise a new tensor of 0s
new_tensor_zeros = torch.zeros_like(initial_tensor)
print(new_tensor_zeros)

# Initialise a new tensor with all elements sampled from a uniform distribution between 0 and 1
new_tensor_rand = torch.rand_like(initial_tensor)
print(new_tensor_rand)

# Initialise a new tensor where all elements are sampled from a normal distribution
new_tensor_randn = torch.randn_like(initial_tensor)
print(new_tensor_randn)

tensor([[4., 5.],
        [6., 7.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.0317, 0.8632],
        [0.0142, 0.9799]])
tensor([[-0.0114, -1.1777],
        [-0.5821, -0.9272]])


In [8]:
shape = (2, 3, 4)

x_zeros = torch.zeros(shape)
print(x_zeros)

x_ones = torch.ones(shape)
print(x_ones)

torch.manual_seed(142)
random = torch.rand(shape)
print(random)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0.9278, 0.3969, 0.7987, 0.3094],
         [0.9321, 0.6097, 0.1127, 0.6895],
         [0.1704, 0.6049, 0.5771, 0.4412]],

        [[0.4884, 0.0448, 0.6659, 0.1933],
         [0.6323, 0.0458, 0.6127, 0.1192],
         [0.0961, 0.9311, 0.6790, 0.5379]]])


In [9]:
x = torch.arange(start=0, end=10, step=2)
print(x)

tensor([0, 2, 4, 6, 8])


^the above is only 1D, there may be an optional argument though...

In [10]:
x = torch.rand(3,2)
print(x.shape)
print(x.dtype)
print(x.size(0))

torch.Size([3, 2])
torch.float32
3


In [11]:
x = torch.Tensor([[11, 12], [13, 14], [15, 16]])
print(x)
# we can change the shape from (2,3) to (3,2)
x_view = x.view(2,3)
print(x_view)

# You can also use torch.reshape() for this
x_reshaped = torch.reshape(x, (2,3))
print(x_reshaped)

tensor([[11., 12.],
        [13., 14.],
        [15., 16.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])


In [12]:
print(x.device)
print(torch.cuda.is_available())

#to leverage the gpu we use
if torch.cuda.is_available():
    x.to('cuda')

cpu
True


In [13]:
#element-wise ops
x = torch.ones(2, 3, 4)
print(x)

print(x + 3)
print(x - 0.5)
print(x*2)
print(x/2)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]])
tensor([[[0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000]]])
tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])
tensor([[[0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.500

In [14]:
x = torch.ones(2, 2, 4)
print(x)

y = torch.ones(2, 2, 4)
print(y)

z_cat = torch.cat([x, y], dim=0)
print(z_cat)
z_cat = torch.cat([x, y], dim=1)
print(z_cat)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [19]:
x = torch.tensor([1, 2, 3], dtype=torch.float)
y = torch.tensor([4, 5, 6], dtype=torch.float)
print(x+y)

# you can also use torch.add()
print(torch.add(x,y))
print(torch.add(x,y).sum())
print(x.dot(y))
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
print(x.shape)
y = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float)
print(y.shape)

# Matrix Multiplication
print(torch.matmul(x, y))

# you can also use torch.mm() 
print(torch.mm(x, y))

# or you can use x@y
print(x@y)

RuntimeError: The size of tensor a (30) must match the size of tensor b (3) at non-singleton dimension 0

In [18]:
print(x)
z = x*10
print(z)

tensor([[10., 20., 30.],
        [40., 50., 60.]])


tensor([[10., 20., 30.],
        [40., 50., 60.]])
